Project: Fix generate_regex to create only one `<item1>` per message
Follows-up 526946e90c. Missed this behavior change between dotnet
and Python. Doesn't appear to affect any wikis or messages at the
moment. Probably because (almost) all the the interface messages
have been frozen in recent changes with overrides deleted from all
wikis and they don't use the same param multiple times by default.

Without the source fix, it fails as follows:

```
Exception: Failed to test-generate regex
^Say what (?<item2>.+?)! I (?<item1>.+?) you, I (?<item1>.+?) dare you\.(?:: (?<comment>.*?))?$
for pulp-fiction; redefinition of group name 'item1' as group 3;
was group 2 at position 54
```

Bug: T327136
Change-Id: Ibbfe7f902e5b66e451cccc9c3aafe43b17067aec