Make CVNBot compatible with Mono 4 and .NET 4.5 for Debian 9
Debian 9 comes with Mono 4. [1] Trying to compile the current version of
CVNBot there produced verious errors.

Highlights from release notes at http://www.mono-project.com/docs/about-mono/releases/4.0.0/
* Mono will now only build the .NET 4.5 assemblies.
  We no longer build the reference assemblies for the .NET 2.0, .NET 3.5 or .NET 4.0 APIs.

Changes:

* Replace old log4net.dll with the latest from https://logging.apache.org/log4net/
  Specifically `/bin/mono/4.0/release` from `log4net-2.0.8-bin-newkey.zip`.

* Remove .csproj.user file (appears unused).

* Remove old Mono.Data.SqliteClient.dll.
  Try to use built-in Mono.Data.Sqlite instead.
  https://developer.xamarin.com/guides/ios/advanced_topics/system.data/
  http://www.mono-project.com/docs/database-access/providers/sqlite/

* Set TargetFrameworkVersion to v4.5, given the older APIs are no longer
  supported. This should fix build errors:
  > CSC: error CS0518: The predefined type `System.Object' is not defined or imported
  > CSC: error CS0518: The predefined type `System.ValueType' is not defined or imported

* Remove redundant <BootstrapperPackage> items in csproj file.

[1] https://packages.debian.org/search?keywords=mono-complete

Ref https://github.com/countervandalism/infrastructure/issues/13.